# version: '3'

networks:
  app:
    driver: bridge

services:
  modsim:
    # build: .
    image: topmaker/modsim
    container_name: modsim
    restart: unless-stopped
    networks:
      - app
    ports:
      - "5020:5020"
