site_name: modsim
repo_url: https://github.com/top-maker/modsim
site_url: https://top-maker.github.io/modsim
site_description: A Simple Modbus TCP Device Simulator used for modpoll tool
site_author: Ying Shaodong
edit_uri: edit/main/docs/
repo_name: top-maker/modsim

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/top-maker/modsim
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/modsim

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
